# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sequencer.ui'
#
# Created: Thu Jul  5 23:55:37 2012
#      by: PyQt4 UI code generator 4.7.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(580, 190)
        Frame.setMinimumSize(QtCore.QSize(580, 180))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans Mono")
        Frame.setFont(font)
        Frame.setFrameShape(QtGui.QFrame.StyledPanel)
        Frame.setFrameShadow(QtGui.QFrame.Raised)
        self.gridLayout_3 = QtGui.QGridLayout(Frame)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_start = QtGui.QPushButton(Frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_start.sizePolicy().hasHeightForWidth())
        self.pushButton_start.setSizePolicy(sizePolicy)
        self.pushButton_start.setMinimumSize(QtCore.QSize(55, 40))
        self.pushButton_start.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pushButton_start.setFont(font)
        self.pushButton_start.setStyleSheet("None")
        self.pushButton_start.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_start.setCheckable(True)
        self.pushButton_start.setAutoDefault(False)
        self.pushButton_start.setDefault(False)
        self.pushButton_start.setFlat(False)
        self.pushButton_start.setObjectName("pushButton_start")
        self.horizontalLayout.addWidget(self.pushButton_start)
        self.pushButton_pause = QtGui.QPushButton(Frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_pause.sizePolicy().hasHeightForWidth())
        self.pushButton_pause.setSizePolicy(sizePolicy)
        self.pushButton_pause.setMinimumSize(QtCore.QSize(55, 40))
        self.pushButton_pause.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pushButton_pause.setFont(font)
        self.pushButton_pause.setCheckable(True)
        self.pushButton_pause.setObjectName("pushButton_pause")
        self.horizontalLayout.addWidget(self.pushButton_pause)
        self.pushButton_stop = QtGui.QPushButton(Frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_stop.sizePolicy().hasHeightForWidth())
        self.pushButton_stop.setSizePolicy(sizePolicy)
        self.pushButton_stop.setMinimumSize(QtCore.QSize(55, 40))
        self.pushButton_stop.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pushButton_stop.setFont(font)
        self.pushButton_stop.setObjectName("pushButton_stop")
        self.horizontalLayout.addWidget(self.pushButton_stop)
        self.pushButton_goto = QtGui.QPushButton(Frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_goto.sizePolicy().hasHeightForWidth())
        self.pushButton_goto.setSizePolicy(sizePolicy)
        self.pushButton_goto.setMinimumSize(QtCore.QSize(55, 40))
        self.pushButton_goto.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pushButton_goto.setFont(font)
        self.pushButton_goto.setObjectName("pushButton_goto")
        self.horizontalLayout.addWidget(self.pushButton_goto)
        self.spinBox_goto = QtGui.QSpinBox(Frame)
        self.spinBox_goto.setObjectName("spinBox_goto")
        self.horizontalLayout.addWidget(self.spinBox_goto)
        self.gridLayout_3.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.tabWidget = QtGui.QTabWidget(Frame)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_points = QtGui.QWidget()
        self.tab_points.setObjectName("tab_points")
        self.gridLayout = QtGui.QGridLayout(self.tab_points)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_points = QtGui.QGridLayout()
        self.gridLayout_points.setObjectName("gridLayout_points")
        self.label_loop_from = QtGui.QLabel(self.tab_points)
        self.label_loop_from.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_loop_from.setObjectName("label_loop_from")
        self.gridLayout_points.addWidget(self.label_loop_from, 4, 0, 1, 1)
        self.spinBox_loop_from = QtGui.QSpinBox(self.tab_points)
        self.spinBox_loop_from.setObjectName("spinBox_loop_from")
        self.gridLayout_points.addWidget(self.spinBox_loop_from, 4, 2, 1, 1)
        self.label_loop_to = QtGui.QLabel(self.tab_points)
        self.label_loop_to.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_loop_to.setObjectName("label_loop_to")
        self.gridLayout_points.addWidget(self.label_loop_to, 5, 0, 1, 1)
        self.spinBox_loop_to = QtGui.QSpinBox(self.tab_points)
        self.spinBox_loop_to.setObjectName("spinBox_loop_to")
        self.gridLayout_points.addWidget(self.spinBox_loop_to, 5, 2, 1, 1)
        self.checkBox_loop_fromlast = QtGui.QCheckBox(self.tab_points)
        self.checkBox_loop_fromlast.setChecked(True)
        self.checkBox_loop_fromlast.setObjectName("checkBox_loop_fromlast")
        self.gridLayout_points.addWidget(self.checkBox_loop_fromlast, 4, 1, 1, 1)
        self.checkBox_loop_tofirst = QtGui.QCheckBox(self.tab_points)
        self.checkBox_loop_tofirst.setChecked(True)
        self.checkBox_loop_tofirst.setObjectName("checkBox_loop_tofirst")
        self.gridLayout_points.addWidget(self.checkBox_loop_tofirst, 5, 1, 1, 1)
        self.label_loop_start = QtGui.QLabel(self.tab_points)
        self.label_loop_start.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_loop_start.setObjectName("label_loop_start")
        self.gridLayout_points.addWidget(self.label_loop_start, 1, 0, 1, 1)
        self.checkBox_point_first = QtGui.QCheckBox(self.tab_points)
        self.checkBox_point_first.setChecked(True)
        self.checkBox_point_first.setObjectName("checkBox_point_first")
        self.gridLayout_points.addWidget(self.checkBox_point_first, 1, 1, 1, 1)
        self.spinBox_point_first = QtGui.QSpinBox(self.tab_points)
        self.spinBox_point_first.setObjectName("spinBox_point_first")
        self.gridLayout_points.addWidget(self.spinBox_point_first, 1, 2, 1, 1)
        self.checkBox_loop_do = QtGui.QCheckBox(self.tab_points)
        self.checkBox_loop_do.setObjectName("checkBox_loop_do")
        self.gridLayout_points.addWidget(self.checkBox_loop_do, 3, 0, 1, 1)
        self.checkBox_point_last = QtGui.QCheckBox(self.tab_points)
        self.checkBox_point_last.setChecked(True)
        self.checkBox_point_last.setObjectName("checkBox_point_last")
        self.gridLayout_points.addWidget(self.checkBox_point_last, 2, 1, 1, 1)
        self.spinBox_point_last = QtGui.QSpinBox(self.tab_points)
        self.spinBox_point_last.setObjectName("spinBox_point_last")
        self.gridLayout_points.addWidget(self.spinBox_point_last, 2, 2, 1, 1)
        self.spinBox_loop_times = QtGui.QSpinBox(self.tab_points)
        self.spinBox_loop_times.setObjectName("spinBox_loop_times")
        self.gridLayout_points.addWidget(self.spinBox_loop_times, 3, 2, 1, 1)
        self.label_loop_end = QtGui.QLabel(self.tab_points)
        self.label_loop_end.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_loop_end.setObjectName("label_loop_end")
        self.gridLayout_points.addWidget(self.label_loop_end, 2, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_points, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_points, "")
        self.tab_speed = QtGui.QWidget()
        self.tab_speed.setObjectName("tab_speed")
        self.radioButton_S3 = QtGui.QRadioButton(self.tab_speed)
        self.radioButton_S3.setGeometry(QtCore.QRect(0, 50, 131, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.radioButton_S3.setFont(font)
        self.radioButton_S3.setObjectName("radioButton_S3")
        self.radioButton_s1 = QtGui.QRadioButton(self.tab_speed)
        self.radioButton_s1.setGeometry(QtCore.QRect(0, 10, 131, 18))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.radioButton_s1.setFont(font)
        self.radioButton_s1.setObjectName("radioButton_s1")
        self.radioButton_S2 = QtGui.QRadioButton(self.tab_speed)
        self.radioButton_S2.setGeometry(QtCore.QRect(0, 30, 131, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.radioButton_S2.setFont(font)
        self.radioButton_S2.setObjectName("radioButton_S2")
        self.tabWidget.addTab(self.tab_speed, "")
        self.tab_trg = QtGui.QWidget()
        self.tab_trg.setObjectName("tab_trg")
        self.radioButton_t2 = QtGui.QRadioButton(self.tab_trg)
        self.radioButton_t2.setGeometry(QtCore.QRect(0, 20, 131, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.radioButton_t2.setFont(font)
        self.radioButton_t2.setObjectName("radioButton_t2")
        self.radioButton_t1 = QtGui.QRadioButton(self.tab_trg)
        self.radioButton_t1.setGeometry(QtCore.QRect(0, 0, 131, 18))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.radioButton_t1.setFont(font)
        self.radioButton_t1.setObjectName("radioButton_t1")
        self.tabWidget.addTab(self.tab_trg, "")
        self.tab_opt = QtGui.QWidget()
        self.tab_opt.setObjectName("tab_opt")
        self.verticalLayout = QtGui.QVBoxLayout(self.tab_opt)
        self.verticalLayout.setObjectName("verticalLayout")
        self.checkBox_loop_do_2 = QtGui.QCheckBox(self.tab_opt)
        self.checkBox_loop_do_2.setObjectName("checkBox_loop_do_2")
        self.verticalLayout.addWidget(self.checkBox_loop_do_2)
        self.tabWidget.addTab(self.tab_opt, "")
        self.gridLayout_3.addWidget(self.tabWidget, 0, 1, 3, 1)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_timen = QtGui.QLabel(Frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_timen.setFont(font)
        self.label_timen.setObjectName("label_timen")
        self.gridLayout_2.addWidget(self.label_timen, 0, 0, 1, 1)
        self.label_time_next = QtGui.QLabel(Frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_time_next.setFont(font)
        self.label_time_next.setObjectName("label_time_next")
        self.gridLayout_2.addWidget(self.label_time_next, 0, 1, 1, 1)
        self.label_timea = QtGui.QLabel(Frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_timea.setFont(font)
        self.label_timea.setObjectName("label_timea")
        self.gridLayout_2.addWidget(self.label_timea, 1, 0, 1, 1)
        self.label_time_akt = QtGui.QLabel(Frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_time_akt.setFont(font)
        self.label_time_akt.setObjectName("label_time_akt")
        self.gridLayout_2.addWidget(self.label_time_akt, 1, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 1, 0, 1, 1)
        self.gridLayout_Values = QtGui.QGridLayout()
        self.gridLayout_Values.setObjectName("gridLayout_Values")
        self.label_akt = QtGui.QLabel(Frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_akt.setFont(font)
        self.label_akt.setObjectName("label_akt")
        self.gridLayout_Values.addWidget(self.label_akt, 0, 0, 1, 1)
        self.label_pos_akt = QtGui.QLabel(Frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_pos_akt.setFont(font)
        self.label_pos_akt.setObjectName("label_pos_akt")
        self.gridLayout_Values.addWidget(self.label_pos_akt, 0, 1, 1, 1)
        self.label_next = QtGui.QLabel(Frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_next.setFont(font)
        self.label_next.setObjectName("label_next")
        self.gridLayout_Values.addWidget(self.label_next, 1, 0, 1, 1)
        self.label_pos_next = QtGui.QLabel(Frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_pos_next.setFont(font)
        self.label_pos_next.setObjectName("label_pos_next")
        self.gridLayout_Values.addWidget(self.label_pos_next, 1, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_Values, 2, 0, 1, 1)

        self.retranslateUi(Frame)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        Frame.setWindowTitle(QtGui.QApplication.translate("Frame", "Frame", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_start.setText(QtGui.QApplication.translate("Frame", "Start", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_pause.setText(QtGui.QApplication.translate("Frame", "Pause", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_stop.setText(QtGui.QApplication.translate("Frame", "Stop", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_goto.setText(QtGui.QApplication.translate("Frame", "GoTo", None, QtGui.QApplication.UnicodeUTF8))
        self.label_loop_from.setText(QtGui.QApplication.translate("Frame", "Loop from", None, QtGui.QApplication.UnicodeUTF8))
        self.label_loop_to.setText(QtGui.QApplication.translate("Frame", "Loop to", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_loop_fromlast.setText(QtGui.QApplication.translate("Frame", "from last", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_loop_tofirst.setText(QtGui.QApplication.translate("Frame", "to first", None, QtGui.QApplication.UnicodeUTF8))
        self.label_loop_start.setText(QtGui.QApplication.translate("Frame", "Start from", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_point_first.setText(QtGui.QApplication.translate("Frame", "from first", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_loop_do.setText(QtGui.QApplication.translate("Frame", "Do Loop", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_point_last.setText(QtGui.QApplication.translate("Frame", "last", None, QtGui.QApplication.UnicodeUTF8))
        self.label_loop_end.setText(QtGui.QApplication.translate("Frame", "End@", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_points), QtGui.QApplication.translate("Frame", "Points", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_S3.setText(QtGui.QApplication.translate("Frame", "time", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_s1.setText(QtGui.QApplication.translate("Frame", "speed from time", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_S2.setText(QtGui.QApplication.translate("Frame", "time from speed", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_speed), QtGui.QApplication.translate("Frame", "Speed", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_t2.setText(QtGui.QApplication.translate("Frame", "Next on Trigger", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_t1.setText(QtGui.QApplication.translate("Frame", "Next on Arrival", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_trg), QtGui.QApplication.translate("Frame", "Trigger", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_loop_do_2.setText(QtGui.QApplication.translate("Frame", "Highlight last point in Editor", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_opt), QtGui.QApplication.translate("Frame", "Options", None, QtGui.QApplication.UnicodeUTF8))
        self.label_timen.setText(QtGui.QApplication.translate("Frame", "Time next ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_time_next.setText(QtGui.QApplication.translate("Frame", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_timea.setText(QtGui.QApplication.translate("Frame", "Time akt", None, QtGui.QApplication.UnicodeUTF8))
        self.label_time_akt.setText(QtGui.QApplication.translate("Frame", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_akt.setText(QtGui.QApplication.translate("Frame", "Akt. Pos.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_pos_akt.setText(QtGui.QApplication.translate("Frame", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_next.setText(QtGui.QApplication.translate("Frame", "Next Pos.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_pos_next.setText(QtGui.QApplication.translate("Frame", "0", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Frame = QtGui.QFrame()
    ui = Ui_Frame()
    ui.setupUi(Frame)
    Frame.show()
    sys.exit(app.exec_())

