# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'controlbuttons.ui'
#
# Created: Fri Jun 29 02:16:24 2012
#      by: PyQt4 UI code generator 4.7.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Frame_controlbuttons(object):
    def setupUi(self, Frame_controlbuttons):
        Frame_controlbuttons.setObjectName("Frame_controlbuttons")
        Frame_controlbuttons.resize(500, 215)
        Frame_controlbuttons.setFrameShape(QtGui.QFrame.StyledPanel)
        Frame_controlbuttons.setFrameShadow(QtGui.QFrame.Raised)
        self.layoutWidget = QtGui.QWidget(Frame_controlbuttons)
        self.layoutWidget.setGeometry(QtCore.QRect(6, 7, 491, 200))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_4 = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_Yp = QtGui.QPushButton(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_Yp.sizePolicy().hasHeightForWidth())
        self.pushButton_Yp.setSizePolicy(sizePolicy)
        self.pushButton_Yp.setMinimumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans Mono")
        font.setPointSize(10)
        self.pushButton_Yp.setFont(font)
        self.pushButton_Yp.setAutoRepeatDelay(500)
        self.pushButton_Yp.setObjectName("pushButton_Yp")
        self.gridLayout.addWidget(self.pushButton_Yp, 0, 1, 1, 1)
        self.pushButton_Xn = QtGui.QPushButton(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_Xn.sizePolicy().hasHeightForWidth())
        self.pushButton_Xn.setSizePolicy(sizePolicy)
        self.pushButton_Xn.setMinimumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans Mono")
        font.setPointSize(10)
        self.pushButton_Xn.setFont(font)
        self.pushButton_Xn.setAutoRepeatDelay(500)
        self.pushButton_Xn.setObjectName("pushButton_Xn")
        self.gridLayout.addWidget(self.pushButton_Xn, 1, 0, 1, 1)
        self.pushButton_Yn = QtGui.QPushButton(self.layoutWidget)
        self.pushButton_Yn.setMinimumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans Mono")
        font.setPointSize(10)
        self.pushButton_Yn.setFont(font)
        self.pushButton_Yn.setAutoRepeatDelay(500)
        self.pushButton_Yn.setObjectName("pushButton_Yn")
        self.gridLayout.addWidget(self.pushButton_Yn, 2, 1, 1, 1)
        self.pushButton_Xp = QtGui.QPushButton(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_Xp.sizePolicy().hasHeightForWidth())
        self.pushButton_Xp.setSizePolicy(sizePolicy)
        self.pushButton_Xp.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_Xp.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans Mono")
        font.setPointSize(10)
        self.pushButton_Xp.setFont(font)
        self.pushButton_Xp.setAutoRepeat(True)
        self.pushButton_Xp.setAutoExclusive(False)
        self.pushButton_Xp.setAutoRepeatDelay(500)
        self.pushButton_Xp.setObjectName("pushButton_Xp")
        self.gridLayout.addWidget(self.pushButton_Xp, 1, 2, 1, 1)
        self.pushButton_Zp = QtGui.QPushButton(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_Zp.sizePolicy().hasHeightForWidth())
        self.pushButton_Zp.setSizePolicy(sizePolicy)
        self.pushButton_Zp.setMinimumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans Mono")
        font.setPointSize(10)
        self.pushButton_Zp.setFont(font)
        self.pushButton_Zp.setAutoRepeatDelay(500)
        self.pushButton_Zp.setObjectName("pushButton_Zp")
        self.gridLayout.addWidget(self.pushButton_Zp, 0, 2, 1, 1)
        self.pushButton_Zn = QtGui.QPushButton(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_Zn.sizePolicy().hasHeightForWidth())
        self.pushButton_Zn.setSizePolicy(sizePolicy)
        self.pushButton_Zn.setMinimumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans Mono")
        font.setPointSize(10)
        self.pushButton_Zn.setFont(font)
        self.pushButton_Zn.setAutoRepeatDelay(500)
        self.pushButton_Zn.setObjectName("pushButton_Zn")
        self.gridLayout.addWidget(self.pushButton_Zn, 2, 2, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout, 0, 0, 2, 1)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_speed = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans Mono")
        font.setPointSize(16)
        self.label_speed.setFont(font)
        self.label_speed.setAlignment(QtCore.Qt.AlignCenter)
        self.label_speed.setObjectName("label_speed")
        self.gridLayout_2.addWidget(self.label_speed, 0, 2, 1, 1)
        self.label_X = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans Mono")
        font.setPointSize(16)
        self.label_X.setFont(font)
        self.label_X.setAlignment(QtCore.Qt.AlignCenter)
        self.label_X.setObjectName("label_X")
        self.gridLayout_2.addWidget(self.label_X, 1, 0, 1, 1)
        self.label_X_s = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans Mono")
        font.setPointSize(16)
        self.label_X_s.setFont(font)
        self.label_X_s.setAlignment(QtCore.Qt.AlignCenter)
        self.label_X_s.setObjectName("label_X_s")
        self.gridLayout_2.addWidget(self.label_X_s, 1, 2, 1, 1)
        self.label_Y = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans Mono")
        font.setPointSize(16)
        self.label_Y.setFont(font)
        self.label_Y.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Y.setObjectName("label_Y")
        self.gridLayout_2.addWidget(self.label_Y, 2, 0, 1, 1)
        self.label_Y_p = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans Mono")
        font.setPointSize(14)
        self.label_Y_p.setFont(font)
        self.label_Y_p.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Y_p.setObjectName("label_Y_p")
        self.gridLayout_2.addWidget(self.label_Y_p, 2, 1, 1, 1)
        self.label_Y_s = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans Mono")
        font.setPointSize(16)
        self.label_Y_s.setFont(font)
        self.label_Y_s.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Y_s.setObjectName("label_Y_s")
        self.gridLayout_2.addWidget(self.label_Y_s, 2, 2, 1, 1)
        self.label_X_p = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans Mono")
        font.setPointSize(14)
        self.label_X_p.setFont(font)
        self.label_X_p.setAlignment(QtCore.Qt.AlignCenter)
        self.label_X_p.setObjectName("label_X_p")
        self.gridLayout_2.addWidget(self.label_X_p, 1, 1, 1, 1)
        self.label_posi = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans Mono")
        font.setPointSize(16)
        self.label_posi.setFont(font)
        self.label_posi.setAlignment(QtCore.Qt.AlignCenter)
        self.label_posi.setObjectName("label_posi")
        self.gridLayout_2.addWidget(self.label_posi, 0, 1, 1, 1)
        self.label_Z = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans Mono")
        font.setPointSize(16)
        self.label_Z.setFont(font)
        self.label_Z.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Z.setObjectName("label_Z")
        self.gridLayout_2.addWidget(self.label_Z, 3, 0, 1, 1)
        self.label_Z_p = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans Mono")
        font.setPointSize(14)
        self.label_Z_p.setFont(font)
        self.label_Z_p.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Z_p.setObjectName("label_Z_p")
        self.gridLayout_2.addWidget(self.label_Z_p, 3, 1, 1, 1)
        self.label_Z_s = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans Mono")
        font.setPointSize(16)
        self.label_Z_s.setFont(font)
        self.label_Z_s.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Z_s.setObjectName("label_Z_s")
        self.gridLayout_2.addWidget(self.label_Z_s, 3, 2, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_2, 0, 1, 1, 1)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_2 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans Mono")
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 0, 0, 1, 1)
        self.spinBox_jog = QtGui.QSpinBox(self.layoutWidget)
        self.spinBox_jog.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans Mono")
        font.setPointSize(16)
        self.spinBox_jog.setFont(font)
        self.spinBox_jog.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_jog.setMinimum(1)
        self.spinBox_jog.setMaximum(99999)
        self.spinBox_jog.setProperty("value", 2000)
        self.spinBox_jog.setObjectName("spinBox_jog")
        self.gridLayout_3.addWidget(self.spinBox_jog, 0, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans Mono")
        font.setPointSize(14)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 1, 0, 1, 1)
        self.spinBox_steps = QtGui.QSpinBox(self.layoutWidget)
        self.spinBox_steps.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans Mono")
        font.setPointSize(16)
        self.spinBox_steps.setFont(font)
        self.spinBox_steps.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_steps.setMinimum(1)
        self.spinBox_steps.setMaximum(99999)
        self.spinBox_steps.setProperty("value", 100)
        self.spinBox_steps.setObjectName("spinBox_steps")
        self.gridLayout_3.addWidget(self.spinBox_steps, 1, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 1, 1, 1, 1)

        self.retranslateUi(Frame_controlbuttons)
        QtCore.QMetaObject.connectSlotsByName(Frame_controlbuttons)

    def retranslateUi(self, Frame_controlbuttons):
        Frame_controlbuttons.setWindowTitle(QtGui.QApplication.translate("Frame_controlbuttons", "Frame", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_Yp.setText(QtGui.QApplication.translate("Frame_controlbuttons", "Y+", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_Yp.setShortcut(QtGui.QApplication.translate("Frame_controlbuttons", "Up", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_Xn.setText(QtGui.QApplication.translate("Frame_controlbuttons", "X-", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_Xn.setShortcut(QtGui.QApplication.translate("Frame_controlbuttons", "Left", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_Yn.setText(QtGui.QApplication.translate("Frame_controlbuttons", "Y-", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_Yn.setShortcut(QtGui.QApplication.translate("Frame_controlbuttons", "Down", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_Xp.setText(QtGui.QApplication.translate("Frame_controlbuttons", "X+", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_Xp.setShortcut(QtGui.QApplication.translate("Frame_controlbuttons", "Right", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_Zp.setText(QtGui.QApplication.translate("Frame_controlbuttons", "Z+", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_Zp.setShortcut(QtGui.QApplication.translate("Frame_controlbuttons", "Up", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_Zn.setText(QtGui.QApplication.translate("Frame_controlbuttons", "Z-", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_Zn.setShortcut(QtGui.QApplication.translate("Frame_controlbuttons", "Up", None, QtGui.QApplication.UnicodeUTF8))
        self.label_speed.setText(QtGui.QApplication.translate("Frame_controlbuttons", " Speed ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_X.setText(QtGui.QApplication.translate("Frame_controlbuttons", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.label_X_s.setText(QtGui.QApplication.translate("Frame_controlbuttons", "-0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_Y.setText(QtGui.QApplication.translate("Frame_controlbuttons", "Y", None, QtGui.QApplication.UnicodeUTF8))
        self.label_Y_p.setText(QtGui.QApplication.translate("Frame_controlbuttons", "-0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_Y_s.setText(QtGui.QApplication.translate("Frame_controlbuttons", "-0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_X_p.setText(QtGui.QApplication.translate("Frame_controlbuttons", "-0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_posi.setText(QtGui.QApplication.translate("Frame_controlbuttons", "Position", None, QtGui.QApplication.UnicodeUTF8))
        self.label_Z.setText(QtGui.QApplication.translate("Frame_controlbuttons", "Z", None, QtGui.QApplication.UnicodeUTF8))
        self.label_Z_p.setText(QtGui.QApplication.translate("Frame_controlbuttons", "-0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_Z_s.setText(QtGui.QApplication.translate("Frame_controlbuttons", "-0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Frame_controlbuttons", "Jog Speed", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Frame_controlbuttons", "Jog Steps", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Frame_controlbuttons = QtGui.QFrame()
    ui = Ui_Frame_controlbuttons()
    ui.setupUi(Frame_controlbuttons)
    Frame_controlbuttons.show()
    sys.exit(app.exec_())

