# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'maincontrol.ui'
#
# Created: Sat Jun 30 01:35:29 2012
#      by: PyQt4 UI code generator 4.7.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(700, 921)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(219, 223, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(254, 255, 248))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(224, 231, 202))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(97, 103, 78))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(129, 138, 104))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(219, 223, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(219, 223, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(224, 231, 205))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(219, 223, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(254, 255, 248))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(224, 231, 202))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(97, 103, 78))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(129, 138, 104))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(219, 223, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(219, 223, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(224, 231, 205))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(97, 103, 78))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(219, 223, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(254, 255, 248))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(224, 231, 202))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(97, 103, 78))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(129, 138, 104))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(97, 103, 78))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(97, 103, 78))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(219, 223, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(219, 223, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(194, 207, 156))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        MainWindow.setPalette(palette)
        MainWindow.setStyleSheet("background-color: rgb(219, 223, 255);")
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_head = QtGui.QLabel(self.centralwidget)
        self.label_head.setGeometry(QtCore.QRect(10, 10, 681, 32))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans Mono")
        font.setPointSize(20)
        self.label_head.setFont(font)
        self.label_head.setAlignment(QtCore.Qt.AlignCenter)
        self.label_head.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.label_head.setObjectName("label_head")
        self.Points = QtGui.QGroupBox(self.centralwidget)
        self.Points.setGeometry(QtCore.QRect(10, 710, 511, 161))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans Mono")
        font.setPointSize(10)
        self.Points.setFont(font)
        self.Points.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.Points.setFlat(False)
        self.Points.setObjectName("Points")
        self.layoutWidget = QtGui.QWidget(self.Points)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 30, 491, 61))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_5 = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_3 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans Mono")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_5.addWidget(self.label_3, 0, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans Mono")
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_5.addWidget(self.label_4, 0, 1, 1, 1)
        self.label_pchkx = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans Mono")
        font.setPointSize(10)
        self.label_pchkx.setFont(font)
        self.label_pchkx.setAlignment(QtCore.Qt.AlignCenter)
        self.label_pchkx.setObjectName("label_pchkx")
        self.gridLayout_5.addWidget(self.label_pchkx, 0, 3, 1, 2)
        self.label_pchky = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans Mono")
        font.setPointSize(10)
        self.label_pchky.setFont(font)
        self.label_pchky.setAlignment(QtCore.Qt.AlignCenter)
        self.label_pchky.setObjectName("label_pchky")
        self.gridLayout_5.addWidget(self.label_pchky, 0, 5, 1, 1)
        self.spinBox_teachPoint = QtGui.QSpinBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans Mono")
        font.setPointSize(10)
        self.spinBox_teachPoint.setFont(font)
        self.spinBox_teachPoint.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.spinBox_teachPoint.setReadOnly(False)
        self.spinBox_teachPoint.setButtonSymbols(QtGui.QAbstractSpinBox.UpDownArrows)
        self.spinBox_teachPoint.setObjectName("spinBox_teachPoint")
        self.gridLayout_5.addWidget(self.spinBox_teachPoint, 1, 0, 1, 1)
        self.spinBox_teach_time = QtGui.QSpinBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans Mono")
        font.setPointSize(10)
        self.spinBox_teach_time.setFont(font)
        self.spinBox_teach_time.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.spinBox_teach_time.setReadOnly(False)
        self.spinBox_teach_time.setButtonSymbols(QtGui.QAbstractSpinBox.UpDownArrows)
        self.spinBox_teach_time.setMinimum(-1)
        self.spinBox_teach_time.setObjectName("spinBox_teach_time")
        self.gridLayout_5.addWidget(self.spinBox_teach_time, 1, 1, 1, 1)
        self.lineEdit_teach_y = QtGui.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans Mono")
        font.setPointSize(10)
        self.lineEdit_teach_y.setFont(font)
        self.lineEdit_teach_y.setAcceptDrops(False)
        self.lineEdit_teach_y.setReadOnly(False)
        self.lineEdit_teach_y.setObjectName("lineEdit_teach_y")
        self.gridLayout_5.addWidget(self.lineEdit_teach_y, 1, 5, 1, 1)
        self.lineEdit_teach_z = QtGui.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans Mono")
        font.setPointSize(10)
        self.lineEdit_teach_z.setFont(font)
        self.lineEdit_teach_z.setAcceptDrops(False)
        self.lineEdit_teach_z.setReadOnly(False)
        self.lineEdit_teach_z.setObjectName("lineEdit_teach_z")
        self.gridLayout_5.addWidget(self.lineEdit_teach_z, 1, 6, 1, 1)
        self.label_pchky_2 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans Mono")
        font.setPointSize(10)
        self.label_pchky_2.setFont(font)
        self.label_pchky_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_pchky_2.setObjectName("label_pchky_2")
        self.gridLayout_5.addWidget(self.label_pchky_2, 0, 6, 1, 1)
        self.label_pchkx_2 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans Mono")
        font.setPointSize(10)
        self.label_pchkx_2.setFont(font)
        self.label_pchkx_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_pchkx_2.setObjectName("label_pchkx_2")
        self.gridLayout_5.addWidget(self.label_pchkx_2, 0, 2, 1, 1)
        self.lineEdit_teach_x = QtGui.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans Mono")
        font.setPointSize(10)
        self.lineEdit_teach_x.setFont(font)
        self.lineEdit_teach_x.setAcceptDrops(False)
        self.lineEdit_teach_x.setReadOnly(False)
        self.lineEdit_teach_x.setObjectName("lineEdit_teach_x")
        self.gridLayout_5.addWidget(self.lineEdit_teach_x, 1, 3, 1, 2)
        self.lineEdit_teach_tfact = QtGui.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans Mono")
        font.setPointSize(10)
        self.lineEdit_teach_tfact.setFont(font)
        self.lineEdit_teach_tfact.setAcceptDrops(False)
        self.lineEdit_teach_tfact.setReadOnly(False)
        self.lineEdit_teach_tfact.setObjectName("lineEdit_teach_tfact")
        self.gridLayout_5.addWidget(self.lineEdit_teach_tfact, 1, 2, 1, 1)
        self.pushButton_teachEdit = QtGui.QPushButton(self.Points)
        self.pushButton_teachEdit.setGeometry(QtCore.QRect(150, 130, 140, 26))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans Mono")
        font.setPointSize(10)
        self.pushButton_teachEdit.setFont(font)
        self.pushButton_teachEdit.setObjectName("pushButton_teachEdit")
        self.pushButton_lancControl = QtGui.QPushButton(self.centralwidget)
        self.pushButton_lancControl.setGeometry(QtCore.QRect(520, 430, 160, 41))
        self.pushButton_lancControl.setObjectName("pushButton_lancControl")
        self.label_ip_port = QtGui.QLabel(self.centralwidget)
        self.label_ip_port.setGeometry(QtCore.QRect(520, 470, 151, 34))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans Mono")
        font.setPointSize(8)
        self.label_ip_port.setFont(font)
        self.label_ip_port.setAlignment(QtCore.Qt.AlignCenter)
        self.label_ip_port.setObjectName("label_ip_port")
        self.label_filename = QtGui.QLabel(self.centralwidget)
        self.label_filename.setGeometry(QtCore.QRect(10, 680, 541, 30))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans Mono")
        font.setPointSize(10)
        self.label_filename.setFont(font)
        self.label_filename.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_filename.setObjectName("label_filename")
        self.frame_com_placeholder = QtGui.QFrame(self.centralwidget)
        self.frame_com_placeholder.setGeometry(QtCore.QRect(520, 50, 160, 150))
        self.frame_com_placeholder.setMinimumSize(QtCore.QSize(160, 150))
        self.frame_com_placeholder.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_com_placeholder.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_com_placeholder.setObjectName("frame_com_placeholder")
        self.frame_control_placeholder = QtGui.QFrame(self.centralwidget)
        self.frame_control_placeholder.setGeometry(QtCore.QRect(10, 50, 500, 215))
        self.frame_control_placeholder.setMinimumSize(QtCore.QSize(500, 215))
        self.frame_control_placeholder.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_control_placeholder.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_control_placeholder.setObjectName("frame_control_placeholder")
        self.frame_drives_placeholder = QtGui.QFrame(self.centralwidget)
        self.frame_drives_placeholder.setGeometry(QtCore.QRect(520, 200, 160, 230))
        self.frame_drives_placeholder.setMinimumSize(QtCore.QSize(160, 230))
        self.frame_drives_placeholder.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_drives_placeholder.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_drives_placeholder.setObjectName("frame_drives_placeholder")
        self.frame_points_placeholder = QtGui.QFrame(self.centralwidget)
        self.frame_points_placeholder.setGeometry(QtCore.QRect(10, 270, 500, 360))
        self.frame_points_placeholder.setMinimumSize(QtCore.QSize(500, 215))
        self.frame_points_placeholder.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_points_placeholder.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_points_placeholder.setObjectName("frame_points_placeholder")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 700, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.action_Load = QtGui.QAction(MainWindow)
        self.action_Load.setObjectName("action_Load")
        self.action_Save = QtGui.QAction(MainWindow)
        self.action_Save.setObjectName("action_Save")
        self.actionSetup = QtGui.QAction(MainWindow)
        self.actionSetup.setObjectName("actionSetup")
        self.action_Drive_Parameter = QtGui.QAction(MainWindow)
        self.action_Drive_Parameter.setObjectName("action_Drive_Parameter")
        self.menuFile.addAction(self.action_Load)
        self.menuFile.addAction(self.action_Save)
        self.menuFile.addAction(self.action_Drive_Parameter)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.pushButton_teachEdit, self.spinBox_teachPoint)
        MainWindow.setTabOrder(self.spinBox_teachPoint, self.spinBox_teach_time)
        MainWindow.setTabOrder(self.spinBox_teach_time, self.lineEdit_teach_tfact)
        MainWindow.setTabOrder(self.lineEdit_teach_tfact, self.lineEdit_teach_x)
        MainWindow.setTabOrder(self.lineEdit_teach_x, self.lineEdit_teach_y)
        MainWindow.setTabOrder(self.lineEdit_teach_y, self.lineEdit_teach_z)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "StepperSuite V0.1 Alpha", None, QtGui.QApplication.UnicodeUTF8))
        self.label_head.setText(QtGui.QApplication.translate("MainWindow", "StepperSuite  V0.1 Alpha", None, QtGui.QApplication.UnicodeUTF8))
        self.Points.setTitle(QtGui.QApplication.translate("MainWindow", "teachdata", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Point", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "avg time nr", None, QtGui.QApplication.UnicodeUTF8))
        self.label_pchkx.setText(QtGui.QApplication.translate("MainWindow", "Position X", None, QtGui.QApplication.UnicodeUTF8))
        self.label_pchky.setText(QtGui.QApplication.translate("MainWindow", "Position Y", None, QtGui.QApplication.UnicodeUTF8))
        self.label_pchky_2.setText(QtGui.QApplication.translate("MainWindow", "Zoom Cmd", None, QtGui.QApplication.UnicodeUTF8))
        self.label_pchkx_2.setText(QtGui.QApplication.translate("MainWindow", "timefactor", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_teachEdit.setText(QtGui.QApplication.translate("MainWindow", "Teach edit ", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_lancControl.setText(QtGui.QApplication.translate("MainWindow", "lanc Control", None, QtGui.QApplication.UnicodeUTF8))
        self.label_ip_port.setText(QtGui.QApplication.translate("MainWindow", "111.222.333.444:4567", None, QtGui.QApplication.UnicodeUTF8))
        self.label_filename.setText(QtGui.QApplication.translate("MainWindow", "no file loaded yet !", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "&File", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Load.setText(QtGui.QApplication.translate("MainWindow", "&Load", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Save.setText(QtGui.QApplication.translate("MainWindow", "&Save", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSetup.setText(QtGui.QApplication.translate("MainWindow", "Drive Parameter", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Drive_Parameter.setText(QtGui.QApplication.translate("MainWindow", "&Drive Parameter", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

